import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

export function AccordionFAQ() {
  return (
    <Accordion
      type="single"
      collapsible
      className="w-full"
      defaultValue="item-1"
    >
      <AccordionItem value="item-1">
        <AccordionTrigger className="text-white">Which is better password vs passphrase?</AccordionTrigger>
        <AccordionContent className="text-zinc-300 pr-10 w-full leading-relaxed">
          <p>
            Due to its increased length and complexity compared to a conventional password, a passphrase is regarded as a more secure form of authentication. The rationale behind passphrases is that longer words or phrases are more resilient against brute force attacks, where attackers try various combinations to crack passwords.
          </p>
        </AccordionContent>
      </AccordionItem>

      <AccordionItem value="item-2">
        <AccordionTrigger className="text-white">How to generate a strong password with Prometheus?</AccordionTrigger>
        <AccordionContent className="text-zinc-300 pr-10 w-full leading-relaxed">
          <p>
            It takes no effort to generate a password on the go with Prometheus. Set the desired length and complexity, and click "Generate". This will create a strong password that meets your specifications.
          </p>
        </AccordionContent>
      </AccordionItem>

      <AccordionItem value="item-3">
        <AccordionTrigger className="text-white">Are the passwords being stored?</AccordionTrigger>
        <AccordionContent className="text-zinc-300 pr-10 w-full leading-relaxed">
          <p>
            No, the passwords generated by Prometheus are not stored. The generator creates passwords on the fly and does not retain any data. This ensures your privacy and security, as no sensitive information is saved or transmitted.
          </p>
        </AccordionContent>
      </AccordionItem>

      <AccordionItem value="item-4">
        <AccordionTrigger className="text-white">How to use the password generator?</AccordionTrigger>
        <AccordionContent className="text-zinc-300 pr-10 w-full leading-relaxed">
          <p>
            Using the password generator is simple. Just set your desired password length and complexity, then click "Generate". The generator will create a strong password that you can copy and use immediately.
          </p>
        </AccordionContent>
      </AccordionItem>

      <AccordionItem value="item-5">
        <AccordionTrigger className="text-white">How often should I update my passwords?</AccordionTrigger>
        <AccordionContent className="text-zinc-300 pr-10 w-full leading-relaxed">
          <p>
            It's recommended to update your passwords every 3–6 months, especially for critical accounts like email, banking, or cloud storage. Prometheus makes it easy to regularly create secure replacements.
          </p>
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  )
}