import React from 'react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

interface FAQItem {
  id: string;
  question: string;
  answer: string;
}

interface AccordionFAQProps {
  defaultValue?: string;
  className?: string;
}

const faqData: FAQItem[] = [
  {
    id: "item-1",
    question: "Which is better password vs passphrase?",
    answer: "Due to its increased length and complexity compared to a conventional password, a passphrase is regarded as a more secure form of authentication. The rationale behind passphrases is that longer words or phrases are more resilient against brute force attacks, where attackers try various combinations to crack passwords."
  },
  {
    id: "item-2", 
    question: "How to generate a strong password with Prometheus?",
    answer: "It takes no effort to generate a password on the go with Prometheus. Set the desired length and complexity, and click \"Generate\" This will create a strong password that meets your specifications."
  },
  {
    id: "item-3",
    question: "Are the passwords being stored?",
    answer: "No, the passwords generated by Prometheus are not stored. The generator creates passwords on the fly and does not retain any data. This ensures your privacy and security, as no sensitive information is saved or transmitted."
  },
  {
    id: "item-4",
    question: "How often should I update my passwords?",
    answer: "It's recommended to update your passwords every 3–6 months, especially for critical accounts like email, banking, or cloud storage. Prometheus makes it easy to regularly create secure replacements."
  }
];

export function AccordionFAQ({ 
  defaultValue = "item-1", 
  className 
}: AccordionFAQProps) {
  return (
    <Accordion
      type="single"
      collapsible
      className={`w-full ${className || ''}`}
      defaultValue={defaultValue}
    >
      {faqData.map((faq) => (
        <AccordionItem key={faq.id} value={faq.id}>
            
          <AccordionTrigger className="text-foreground font-heading text-left">
            {faq.question}
          </AccordionTrigger>
          <AccordionContent className="text-muted-foreground font-body pr-10 w-full leading-relaxed">
            <p>{faq.answer}</p>
          </AccordionContent>
        </AccordionItem>
      ))}
    </Accordion>
  );
}